#!/usr/bin/env bash
# LogSentry fleet onboarding — attach a new machine to the SOC hub.
#
# The hub (this host) ingests via:
#   syslog  :514/tcp+udp     → logsentry-engine (rsyslog forwarders)
#   HTTP    :8080/ingest     → logsentry-api   (multipart file upload)
#   Augur   :8000            → agent registration/heartbeat/events
#   ThreatPulse :8081        → SIEM webhook (via /api/siem/api/v1)
#
# Modes:
#   syslog   (default)  Any Linux host with rsyslog — forwarder config only.
#                       Best for LXC/Proxmox VMs, desktops, servers.
#   http                Hosts/containers without rsyslog — installs a small
#                       systemd forwarder that tails log files → :8080/ingest.
#   agent               Full LogSentry engine on the target (local detection,
#                       offline buffering, registers as its own Augur agent).
#
# Usage:
#   deploy/onboard.sh --target user@host --mode syslog [options]
#
# Options:
#   --target HOST       SSH target (user@host or ssh alias)
#   --mode MODE         syslog|http|agent (default: syslog)
#   --name NAME         Friendly host label (default: target hostname)
#   --hub IP[:PORT]     Hub address for forwarders (default: 192.168.1.30)
#   --remote            Use the hub Tailscale IP (100.109.86.28) for WAN hosts
#   --api-key KEY       Hub API key (agent mode only, optional)
#   --facility SPEC     rsyslog facility selector (default: *.*)
#   --skip-verify       Don't send a test log / verify ingestion
#   -h, --help          Show this help
#
# Examples:
#   # Local LXC VM on the LAN
#   bash deploy/onboard.sh --target root@lxc-vm-07 --mode syslog --name lxc-vm-07
#   # Remote VPS over Tailscale
#   bash deploy/onboard.sh --target root@vps-01 --mode syslog --name vps-01 --remote
#   # Docker container / host without rsyslog
#   bash deploy/onboard.sh --target root@docker-host --mode http --name docker-host
#   # Full agent on a beefy server
#   bash deploy/onboard.sh --target root@srv-02 --mode agent --name srv-02 --remote
set -uo pipefail

HUB_LAN="192.168.1.30"
HUB_TS="100.109.86.28"

TARGET=""
MODE="syslog"
NAME=""
HUB=""
REMOTE=false
API_KEY=""
FACILITY="*.*"
VERIFY=true

RED='\033[0;31m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; NC='\033[0m'
log()  { echo -e "${GREEN}[+]${NC} $1"; }
warn() { echo -e "${RED}[!]${NC} $1"; }
info() { echo -e "${CYAN}[*]${NC} $1"; }

usage() { sed -n '2,37p' "$0" | sed 's/^# \{0,1\}//'; }

while [[ $# -gt 0 ]]; do
    case "$1" in
        --target) TARGET="$2"; shift 2 ;;
        --mode)   MODE="$2"; shift 2 ;;
        --name)   NAME="$2"; shift 2 ;;
        --hub)    HUB="$2"; shift 2 ;;
        --remote) REMOTE=true; shift ;;
        --api-key) API_KEY="$2"; shift 2 ;;
        --facility) FACILITY="$2"; shift 2 ;;
        --skip-verify) VERIFY=false; shift ;;
        -h|--help) usage; exit 0 ;;
        *) warn "Unknown option: $1 (use --help)"; exit 1 ;;
    esac
done

if [[ -z "$TARGET" ]]; then
    warn "Missing --target (user@host)"
    usage
    exit 1
fi

# ── Resolve hub endpoint ────────────────────────────────────────
if [[ -z "$HUB" ]]; then
    if $REMOTE; then HUB="$HUB_TS"; else HUB="$HUB_LAN"; fi
fi
HUB_IP="${HUB%:*}"     # strip :port if given

if [[ -z "$NAME" ]]; then
    NAME="$(ssh -o ConnectTimeout=10 "$TARGET" 'hostname' 2>/dev/null | tr -d '\r\n' || echo "$TARGET")"
fi

info "Onboarding '$NAME' ($TARGET) → hub $HUB (mode: $MODE)"

# ── Remote helpers ──────────────────────────────────────────────
# run_remote: executes the script in $1 on the target. Allocates a TTY when
# stdin is a terminal so interactive sudo prompts work on the target.
run_remote() {
    local ssh_opts="-o ConnectTimeout=15 -o ServerAliveInterval=10"
    if [[ -t 0 ]]; then
        ssh_opts="$ssh_opts -t"
    fi
    ssh $ssh_opts "$TARGET" 'bash -s' <<EOF
set -uo pipefail
$1
EOF
}

# ── Mode: syslog ────────────────────────────────────────────────
onboard_syslog() {
    local cfg="/etc/rsyslog.d/90-logsentry.conf"
    info "Installing rsyslog forwarder on $TARGET → ${HUB_IP}:514/tcp"
    local out
    out="$(run_remote "
S=\$(id -u)
[ \$S -ne 0 ] && sudo_cmd=sudo || sudo_cmd=
\$sudo_cmd mkdir -p /etc/rsyslog.d
cat > /tmp/90-logsentry.conf <<CFG
# LogSentry forwarder (generated by deploy/onboard.sh for host '$NAME')
# NOTE: omfwd is auto-loaded for @/@@ actions — do not add module(load="omfwd"),
#       that fails on distros (e.g. Alpine) where it is statically linked.
\\\$ActionQueueType LinkedList
\\\$ActionQueueFileName logsentry
\\\$ActionQueueSaveOnShutdown on
\\\$ActionResumeRetryCount -1
$FACILITY @@$HUB_IP:514;RSYSLOG_SyslogProtocol23Format
CFG
\$sudo_cmd cp /tmp/90-logsentry.conf \$cfg
\$sudo_cmd chmod 644 \$cfg
if command -v systemctl >/dev/null 2>&1; then
    \$sudo_cmd systemctl restart rsyslog || \$sudo_cmd systemctl restart syslog
else
    \$sudo_cmd service rsyslog restart
fi
echo FORWARDER_OK
")"
    echo "$out"
    if [[ "$out" == *FORWARDER_OK* ]]; then
        log "rsyslog forwarder installed on $TARGET"
    else
        warn "rsyslog forwarder may have failed on $TARGET (see output above)"
    fi
}

# ── Mode: http (tail + POST /ingest) ───────────────────────────
onboard_http() {
    local dir="/opt/logsentry-forward"
    local unit="/etc/systemd/system/logsentry-forward.service"
    info "Installing HTTP log forwarder on $TARGET → http://$HUB_IP:8080/ingest"
    local out
    out="$(run_remote "
S=\$(id -u)
[ \$S -ne 0 ] && sudo_cmd=sudo || sudo_cmd=
\$sudo_cmd mkdir -p $dir
cat > $dir/forward.py <<'PY'
#!/usr/bin/env python3
import os, sys, glob, time, subprocess, urllib.request

HUB = os.environ.get('LOGSENTRY_HUB', 'http://${HUB_IP}:8080')
FILES = [f for f in os.environ.get('LOGSENTRY_FILES', '/var/log/*.log').split(',') if f.strip()]
BATCH = 200
INTERVAL = 5
NAME = os.environ.get('LOGSENTRY_NAME', 'unknown')

def resolve(paths):
    out = []
    for p in paths:
        if glob.has_magic(p):
            out.extend(glob.glob(p))
        elif os.path.isfile(p):
            out.append(p)
    return out

def multipart(field, filename, content):
    boundary = '----logsentry-forward'
    body = (
        f'--{boundary}\r\nContent-Disposition: form-data; name=\"{field}\"; '
        f'filename=\"{filename}\"\r\nContent-Type: application/octet-stream\r\n\r\n'
        f'{content}\r\n--{boundary}--\r\n'
    ).encode()
    return body, f'multipart/form-data; boundary={boundary}'

def tail(path):
    if not os.path.exists(path):
        return None
    return subprocess.Popen(['tail', '-n', '0', '-F', path],
                            stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
                            text=True, errors='replace')

def main():
    procs = [p for p in (tail(f) for f in resolve(FILES)) if p]
    # Read the tail pipe non-blocking so the periodic flush below can run
    # even while no new lines are arriving (a blocking readline would stall
    # the loop until the batch threshold is hit).
    for p in procs:
        try:
            os.set_blocking(p.stdout.fileno(), False)
        except Exception:
            pass
    buf = []
    def flush():
        if not buf:
            return
        data = ''.join(buf)
        buf.clear()
        body, ctype = multipart('file', NAME + '.log', data)
        req = urllib.request.Request(HUB + '/ingest', data=body, method='POST',
                                     headers={'Content-Type': ctype})
        try:
            with urllib.request.urlopen(req, timeout=15) as r:
                pass
        except Exception as e:
            sys.stderr.write('forward error: %s\n' % e)
    while True:
        time.sleep(INTERVAL)
        for p in procs:
            try:
                while True:
                    try:
                        line = p.stdout.readline()
                    except BlockingIOError:
                        break
                    if not line:
                        break
                    buf.append(line)
                    if len(buf) >= BATCH:
                        flush()
            except Exception:
                pass
        flush()

main()
PY
\$sudo_cmd chmod 755 $dir/forward.py
cat > /tmp/logsentry-forward.service <<UNIT
[Unit]
Description=LogSentry HTTP log forwarder
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/bin/env python3 $dir/forward.py
Environment=LOGSENTRY_HUB=http://$HUB_IP:8080
Environment=LOGSENTRY_NAME=$NAME
Environment=LOGSENTRY_FILES=/var/log/*.log
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
UNIT
\$sudo_cmd cp /tmp/logsentry-forward.service $unit
\$sudo_cmd systemctl daemon-reload
\$sudo_cmd systemctl enable --now logsentry-forward
echo HTTP_FORWARDER_OK
")"
    echo "$out"
    if [[ "$out" == *HTTP_FORWARDER_OK* ]]; then
        log "HTTP forwarder installed on $TARGET"
    else
        warn "HTTP forwarder may have failed on $TARGET (see output above)"
    fi
}

# ── Mode: agent (full engine) ──────────────────────────────────
onboard_agent() {
    info "Installing full LogSentry engine on $TARGET (hub $HUB_IP)"
    local augur_url="http://$HUB_IP:8000"
    local tp_url="http://$HUB_IP:8081/api/siem/api/v1"
    # Ship the LOCAL installer: the repo on GitHub can lag behind the working
    # tree, so curl-ing $REPO/raw/main/... may serve a stale install.sh.
    local installer="$(cd "$(dirname "$0")" && pwd)/install.sh"
    if [[ ! -f "$installer" ]]; then
        warn "installer not found next to onboard.sh ($installer)"
        return 1
    fi
    info "Shipping installer $installer to $TARGET"
    if ! scp -o ConnectTimeout=15 "$installer" "$TARGET:/tmp/logsentry-install.sh"; then
        warn "could not copy installer to $TARGET"
        return 1
    fi
    local out
    out="$(run_remote "
S=\$(id -u)
[ \$S -ne 0 ] && sudo_cmd=sudo || sudo_cmd=
set -euo pipefail
\$sudo_cmd bash /tmp/logsentry-install.sh --augur-url '$augur_url' --threatpulse-url '$tp_url'
echo AGENT_OK
")"
    echo "$out"
    if [[ "$out" == *AGENT_OK* ]]; then
        log "LogSentry engine installed on $TARGET"
    else
        warn "agent install may have failed on $TARGET (see output above)"
    fi
}

# ── Verify ─────────────────────────────────────────────────────
verify() {
    info "Sending test log line and verifying ingestion..."
    run_remote "
S=\$(id -u)
[ \$S -ne 0 ] && sudo_cmd=sudo || sudo_cmd=
\$sudo_cmd logger -t logsentry-onboard 'onboard test for $NAME'
" >/dev/null 2>&1
    sleep 8
    echo "--- recent logs in LogSentry DB ---"
    # docker exec does not forward a heredoc on stdin here, so ship the
    # verify script via docker cp and run it from inside the container.
    cat > /tmp/logsentry-verify.py <<'PY'
import sys, psycopg2
name, mode = sys.argv[1], sys.argv[2]
conn = psycopg2.connect('postgresql://logsentry:aba83d7fc050022981216763e6fdd8bf@192.168.1.33:5432/logsentry')
cur = conn.cursor()
# The test line itself: confirms end-to-end delivery from this target.
cur.execute("""
  select id, host, source, message from logs
  where message like '%%onboard test for ' || %s || '%%'
    and timestamp > now() - interval '3 minutes'
  order by id desc limit 3
""", (name,))
test = cur.fetchall()
print('test line:')
if not test:
    print('  NOT FOUND yet (forwarder may still be starting / hub unreachable)')
    found = False
else:
    found = True
    for r in test:
        print(f"  id={r[0]}  host={r[1] or '(none)'}  source={r[2]}  msg={r[3][:60]}")
print()
print('recent ingest (last 2 min):')
cur.execute("""
  select host, source, count(*) from logs
  where timestamp > now() - interval '2 minutes'
  group by host, source order by 3 desc limit 10
""")
rows = cur.fetchall()
if not rows:
    print('  (no logs)')
else:
    for r in rows:
        print(f'  {r[0] or "(none)":20} {r[1]:10} {r[2]:6}')
if mode == 'syslog':
    print()
    print('note: for syslog mode the DB host column is the sender IP;')
    print('      the parsed hostname lives in message/parsed data.')
sys.exit(0 if found else 1)
PY
    docker cp /tmp/logsentry-verify.py logsentry-engine:/tmp/logsentry-verify.py >/dev/null
    docker exec logsentry-engine /app/.venv/bin/python /tmp/logsentry-verify.py "$NAME" "$MODE"
    local rc=$?
    docker exec logsentry-engine rm -f /tmp/logsentry-verify.py >/dev/null
    rm -f /tmp/logsentry-verify.py
    return $rc
}

# ── Run ────────────────────────────────────────────────────────
case "$MODE" in
    syslog) onboard_syslog ;;
    http)   onboard_http ;;
    agent)  onboard_agent ;;
    *) warn "Unknown mode: $MODE"; exit 1 ;;
esac

if $VERIFY; then verify; fi
echo ""
log "Onboarded '$NAME' → hub $HUB (mode: $MODE)"
echo "  Next: watch events in Augur (http://localhost:80) and ThreatPulse (http://localhost:8081)"
