apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logsentry.fullname" . }}
type: Opaque
stringData:
  LOGSENTRY_API_KEY: {{ .Values.apiKey | quote }}
  AUGUR_API_KEY: {{ .Values.augur.apiKey | quote }}
  THREATPULSE_API_KEY: {{ .Values.threatpulse.apiKey | quote }}
